# Informações pegas daqui: https://www.geeksforgeeks.org/50-common-ports-you-should-know/

ports_info = {
    7: {"Service name": "Echo", "Transport protocol": ["TCP", "UDP"], "Description": "Echo service"},
    20: {"Service name": "FTP-data", "Transport protocol": ["TCP", "SCTP"], "Description": "File Transfer Protocol data transfer"},
    21: {"Service name": "FTP", "Transport protocol": ["TCP", "UDP", "SCTP"], "Description": "File Transfer Protocol (FTP) control connection"},
    22: {"Service name": "SSH-SCP", "Transport protocol": ["TCP", "UDP", "SCTP"], "Description": "Secure Shell, secure logins, file transfers (scp, sftp), and port forwarding"},
    23: {"Service name": "Telnet", "Transport protocol": ["TCP"], "Description": "Telnet protocol—unencrypted text communications"},
    25: {"Service name": "SMTP", "Transport protocol": ["TCP"], "Description": "Simple Mail Transfer Protocol, used for email routing between mail servers"},
    53: {"Service name": "DNS", "Transport protocol": ["TCP", "UDP"], "Description": "Domain Name System name resolver"},
    69: {"Service name": "TFTP", "Transport protocol": ["UDP"], "Description": "Trivial File Transfer Protocol"},
    80: {"Service name": "HTTP", "Transport protocol": ["TCP", "UDP", "SCTP"], "Description": "Hypertext Transfer Protocol (HTTP) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP"},
    88: {"Service name": "Kerberos", "Transport protocol": ["TCP", "UDP"], "Description": "Network authentication system"},
    102: {"Service name": "Iso-tsap", "Transport protocol": ["TCP"], "Description": "ISO Transport Service Access Point (TSAP) Class 0 protocol"},
    110: {"Service name": "POP3", "Transport protocol": ["TCP"], "Description": "Post Office Protocol, version 3 (POP3)"},
    135: {"Service name": "Microsoft EPMAP", "Transport protocol": ["TCP", "UDP"], "Description": "Microsoft EPMAP (End Point Mapper), also known as DCE/RPC Locator service, used to remotely manage services including DHCP server, DNS server, and WINS. Also used by DCOM"},
    137: {"Service name": "NetBIOS-ns", "Transport protocol": ["TCP", "UDP"], "Description": "NetBIOS Name Service, used for name registration and resolution"},
    139: {"Service name": "NetBIOS-ssn", "Transport protocol": ["TCP", "UDP"], "Description": "NetBIOS Session Service"},
    143: {"Service name": "IMAP4", "Transport protocol": ["TCP", "UDP"], "Description": "Internet Message Access Protocol (IMAP), management of electronic mail messages on a server"},
    381: {"Service name": "HP Openview", "Transport protocol": ["TCP", "UDP"], "Description": "HP data alarm manager"},
    383: {"Service name": "HP Openview", "Transport protocol": ["TCP", "UDP"], "Description": "HP performance data collector"},
    443: {"Service name": "HTTP over SSL", "Transport protocol": ["TCP", "UDP", "SCTP"], "Description": "Hypertext Transfer Protocol Secure (HTTPS) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP"},
    464: {"Service name": "Kerberos", "Transport protocol": ["TCP", "UDP"], "Description": "Kerberos Change/Set password"},
    465: {"Service name": "SMTP over TLS/SSL, SSM", "Transport protocol": ["TCP"], "Description": "Authenticated SMTP over TLS/SSL (SMTPS), URL Rendezvous Directory for SSM (Cisco protocol)"},
    587: {"Service name": "SMTP", "Transport protocol": ["TCP"], "Description": "Email message submission"},
    593: {"Service name": "Microsoft DCOM", "Transport protocol": ["TCP", "UDP"], "Description": "HTTP RPC Ep Map, Remote procedure call over Hypertext Transfer Protocol, often used by Distributed Component Object Model services and Microsoft Exchange Server"},
    636: {"Service name": "LDAP over TLS/SSL", "Transport protocol": ["TCP", "UDP"], "Description": "Lightweight Directory Access Protocol over TLS/SSL"},
    691: {"Service name": "MS Exchange", "Transport protocol": ["TCP"], "Description": "MS Exchange Routing"},
    902: {"Service name": "VMware Server", "Transport protocol": "unofficial", "Description": "VMware ESXi"},
    989: {"Service name": "FTP over SSL", "Transport protocol": ["TCP", "UDP"], "Description": "FTPS Protocol (data), FTP over TLS/SSL"},
    990: {"Service name": "FTP over SSL", "Transport protocol": ["TCP", "UDP"], "Description": "FTPS Protocol (control), FTP over TLS/SSL"},
    993: {"Service name": "IMAP4 over SSL", "Transport protocol": ["TCP"], "Description": "Internet Message Access Protocol over TLS/SSL (IMAPS)"},
    995: {"Service name": "POP3 over SSL", "Transport protocol": ["TCP", "UDP"], "Description": "Post Office Protocol 3 over TLS/SSL"},
    1025: {"Service name": "Microsoft RPC", "Transport protocol": ["TCP"], "Description": "Microsoft operating systems tend to allocate one or more unsuspected, publicly exposed services (probably DCOM, but who knows) among the first handful of ports immediately above the end of the service port range (1024+)."},
    1194: {"Service name": "OpenVPN", "Transport protocol": ["TCP", "UDP"], "Description": "OpenVPN"},
    1337: {"Service name": "WASTE", "Transport protocol": "unofficial", "Description": "WASTE Encrypted File Sharing Program"},
    1589: {"Service name": "Cisco VQP", "Transport protocol": ["TCP", "UDP"], "Description": "Cisco VLAN Query Protocol (VQP)"},
    1725: {"Service name": "Steam", "Transport protocol": ["UDP"], "Description": "Valve Steam Client uses port 1725"},
    2082: {"Service name": "cPanel", "Transport protocol": "unofficial", "Description": "cPanel default"},
    2083: {"Service name": "radsec, cPanel", "Transport protocol": ["TCP", "UDP"], "Description": "Secure RADIUS Service (radsec), cPanel default SSL"},
    2483: {"Service name": "Oracle DB", "Transport protocol": ["TCP", "UDP"], "Description": "Oracle database listening for insecure client connections to the listener, replaces port 1521"},
    2484: {"Service name": "Oracle DB", "Transport protocol": ["TCP", "UDP"], "Description": "Oracle database listening for SSL client connections to the listener"},
    2967: {"Service name": "Symantec AV", "Transport protocol": ["TCP", "UDP"], "Description": "Symantec System Center agent (SSC-AGENT)"},
    3074: {"Service name": "XBOX Live", "Transport protocol": ["TCP", "UDP"], "Description": "Xbox LIVE and Games for Windows – Live"},
    3306: {"Service name": "MySQL", "Transport protocol": ["TCP"], "Description": "MySQL database system"},
    3724: {"Service name": "World of Warcraft", "Transport protocol": ["TCP", "UDP"], "Description": "Some Blizzard games, Unofficial Club Penguin Disney online game for kids"},
    4664: {"Service name": "Google Desktop", "Transport protocol": "unofficial", "Description": "Google Desktop Search"},
    5432: {"Service name": "PostgreSQL", "Transport protocol": ["TCP"], "Description": "PostgreSQL database system"},
    5900: {"Service name": "RFB/VNC Server", "Transport protocol": ["TCP", "UDP"], "Description": "virtual Network Computing (VNC) Remote Frame Buffer RFB protocol"},
    "6665-6669": {"Service name": "IRC", "Transport protocol": ["TCP"], "Description": "Internet Relay Chat"},
    6881: {"Service name": "BitTorrent", "Transport protocol": "unofficial", "Description": "BitTorrent is part of the full range of ports used most often"},
    6999: {"Service name": "BitTorrent", "Transport protocol": "unofficial", "Description": "BitTorrent is part of the full range of ports used most often"},
    6970: {"Service name": "Quicktime", "Transport protocol": "unofficial", "Description": "QuickTime Streaming Server"},
    8086: {"Service name": "Kaspersky AV", "Transport protocol": ["TCP"], "Description": "Kaspersky AV Control Center"},
    8087: {"Service name": "Kaspersky AV", "Transport protocol": ["UDP"], "Description": "Kaspersky AV Control Center"},
    8222: {"Service name": "VMware Server", "Transport protocol": ["TCP", "UDP"], "Description": "VMware Server Management User Interface (insecure Web interface)."},
    9100: {"Service name": "PDL", "Transport protocol": ["TCP"], "Description": "PDL Data Stream, used for printing to certain network printers."},
    10000: {"Service name": "BackupExec", "Transport protocol": "unofficial", "Description": "Webmin, Web-based Unix/Linux system administration tool (default port)"},
    12345: {"Service name": "NetBus", "Transport protocol": "unofficial", "Description": "NetBus remote administration tool (often Trojan horse)."},
    27374: {"Service name": "Sub7", "Transport protocol": "unofficial", "Description": "Sub7 default"},
    31337: {"Service name": "Back Orifice", "Transport protocol": "unofficial", "Description": "Back Orifice 2000 remote administration tools"},
}
